
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xef\x19\xb0\xae\xb8!\x008a\xec,\x85JK\xa0j'
    
_lr_action_items = {'COMMA':([3,5,6,7,8,],[-2,-5,-6,9,-1,]),'RPAREN':([2,3,4,5,6,7,8,10,],[3,-2,8,-5,-6,-4,-1,-3,]),'NUMBER':([2,9,],[6,6,]),'LPAREN':([0,2,9,],[2,2,2,]),'$end':([1,3,8,],[0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'listelement':([2,9,],[7,7,]),'list':([0,2,9,],[1,5,5,]),'sequence':([2,9,],[4,10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> list","S'",1,None,None,None),
  ('list -> LPAREN sequence RPAREN','list',3,'p_list','/Users/richardhart/Dropbox/Drexel/Spring2013/ProgrammingLanguages/Assignment_1_Final/Part_1_2/Part2.py',40),
  ('list -> LPAREN RPAREN','list',2,'p_list','/Users/richardhart/Dropbox/Drexel/Spring2013/ProgrammingLanguages/Assignment_1_Final/Part_1_2/Part2.py',41),
  ('sequence -> listelement COMMA sequence','sequence',3,'p_sequence','/Users/richardhart/Dropbox/Drexel/Spring2013/ProgrammingLanguages/Assignment_1_Final/Part_1_2/Part2.py',48),
  ('sequence -> listelement','sequence',1,'p_sequence','/Users/richardhart/Dropbox/Drexel/Spring2013/ProgrammingLanguages/Assignment_1_Final/Part_1_2/Part2.py',49),
  ('listelement -> list','listelement',1,'p_listelement','/Users/richardhart/Dropbox/Drexel/Spring2013/ProgrammingLanguages/Assignment_1_Final/Part_1_2/Part2.py',56),
  ('listelement -> NUMBER','listelement',1,'p_listelement','/Users/richardhart/Dropbox/Drexel/Spring2013/ProgrammingLanguages/Assignment_1_Final/Part_1_2/Part2.py',57),
]
