
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 19 08:46:19 EDT 2013
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int COMMA = 2;
  public static final int RPAREN = 4;
  public static final int error = 1;
  public static final int NUMBER = 5;
  public static final int LPAREN = 3;
  public static final int EOF = 0;
}

