
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xcej\x91a\xa2\x98\xd40\xd8hn\xb8Z\x9b\xa8U'

_lr_action_items = {'RPAREN':([2,9,10,11,12,13,14,15,],[-6,15,-3,-5,-1,-2,-4,-7,]),'NUMBER':([0,3,4,5,6,7,8,],[2,2,2,2,2,2,2,]),'TIMES':([1,2,9,10,11,12,13,14,15,],[8,-6,8,-3,-5,8,8,-4,-7,]),'PLUS':([1,2,9,10,11,12,13,14,15,],[6,-6,6,-3,-5,-1,-2,-4,-7,]),'LPAREN':([0,3,4,5,6,7,8,],[3,3,3,3,3,3,3,]),'DIV':([1,2,9,10,11,12,13,14,15,],[5,-6,5,-3,-5,5,5,-4,-7,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[4,7,-6,4,4,4,4,4,4,7,-3,-5,-1,-2,-4,-7,]),'$end':([1,2,10,11,12,13,14,15,],[0,-6,-3,-5,-1,-2,-4,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,4,5,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('expr',3,'p_add','./exp1.py',93),
  ('expr',3,'p_sub','./exp1.py',97),
  ('expr',2,'p_expr2uminus','./exp1.py',101),
  ('expr',3,'p_mult_div','./exp1.py',106),
  ('expr',3,'p_mult_div','./exp1.py',107),
  ('expr',1,'p_expr2NUM','./exp1.py',117),
  ('expr',3,'p_parens','./exp1.py',121),
]
